Repository gamer-project/gamer, pull requests merged in 2023-08, with the labels that each got.

#228 Support OPT__RESET_FLUID_INIT for OPT__INIT=3
  src/Auxiliary/Aux_Check_Parameter.cpp
  src/Init/Init_ByFile.cpp
Labels: enhancement

#206 MHM supports MHD
  include/CUFLU.h
  src/Auxiliary/Aux_Check_Parameter.cpp
  src/Makefile
  src/Model_Hydro/CPU_Hydro/CPU_FluidSolver_CTU.cpp
  src/Model_Hydro/CPU_Hydro/CPU_FluidSolver_MHM.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_ConstrainedTransport.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_DataReconstruction.cpp
  src/configure.py
Labels: enhancement, mhd

#229 Support large FFT
  src/Output/Output_BasePowerSpectrum.cpp
  src/SelfGravity/CPU_Poisson/CPU_PoissonSolver_FFT.cpp
  src/SelfGravity/Init_GreenFuncK.cpp
Labels: enhancement

#212 Separate the flux fix-up code in `Hydro_ComputeFlux()` to a single function.
  src/Model_Hydro/CPU_Hydro/CPU_FluidSolver_CTU.cpp
  src/Model_Hydro/CPU_Hydro/CPU_FluidSolver_MHM.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_ComputeFlux.cpp
Labels: enhancement, hydro
