Repository gamer-project/gamer, pull requests merged in 2023-07, with the labels that each got.

#223 Add rpath in Makefile_base
  src/Makefile_base
Labels: enhancement, compilation

#224 Bugfix
  include/AMR.h
  src/Auxiliary/Aux_Check_PatchAllocate.cpp
  src/LoadBalance/LB_Init_LoadBalance.cpp
Labels: bugfix

#226 Update FFTW and GSL interface
  include/FFTW.h
  include/GSL.h
  src/Init/Init_FFTW.cpp
  src/Output/Output_BasePowerSpectrum.cpp
  src/SelfGravity/CPU_Poisson/CPU_PoissonSolver_FFT.cpp
  src/SelfGravity/End_MemFree_PoissonGravity.cpp
  src/SelfGravity/Init_GreenFuncK.cpp
Labels: enhancement, general

#220 Add function to find refined patches to LB_GatherTree
  include/GatherTree.h
  src/LoadBalance/LB_GatherTree.cpp
Labels: enhancement, parallel, amr

#225 Reset B fields
  example/test_problem/Hydro/BlastWave/Input__Flag_User
  example/test_problem/Hydro/BlastWave/Input__Parameter
  example/test_problem/Hydro/BlastWave/Input__TestProb
  example/test_problem/Hydro/BlastWave/README
  example/test_problem/Hydro/BlastWave/plot_script/plot_profile.gpt
  example/test_problem/Hydro/BlastWave/plot_script/plot_slice_B.py
  example/test_problem/Hydro/BlastWave/plot_script/plot_slice_gas.py
  include/Prototype.h
  include/TestProb.h
  src/Auxiliary/Aux_Check_Parameter.cpp
  src/Auxiliary/Aux_TakeNote.cpp
  src/Fluid/Flu_ResetByUser.cpp
  src/Main/EvolveLevel.cpp
  src/Makefile
  src/Makefile_base
  src/Model_Hydro/Hydro_Init_ByFunction_AssignData.cpp
  src/Model_Hydro/MHD_Init_BField_ByVecPot_Function.cpp
  src/Model_Hydro/MHD_ResetByUser.cpp
  src/TestProblem/Hydro/BlastWave/Flag_BlastWave.cpp
  src/TestProblem/Hydro/BlastWave/Init_TestProb_Hydro_BlastWave.cpp
  src/TestProblem/Hydro/BlastWave/MHD_ResetByUser_BlastWave.cpp
  src/TestProblem/Hydro/Bondi/Flu_ResetByUser_Bondi.cpp
  src/TestProblem/Hydro/Bondi/Init_TestProb_Hydro_Bondi.cpp
Labels: enhancement, mhd
