Repository gamer-project/gamer, pull requests merged in 2023-10, with the labels that each got.

#239 Adjust the output format using runtime parameter.
  example/test_problem/Template/Input__Parameter
  include/Global.h
  include/HDF5_Typedef.h
  include/Macro.h
  src/Auxiliary/Aux_Check_Parameter.cpp
  src/Auxiliary/Aux_TakeNote.cpp
  src/Init/Init_ByRestart_HDF5.cpp
  src/Init/Init_Load_Parameter.cpp
  src/Init/Init_ResetParameter.cpp
  src/Main/Main.cpp
  src/Output/Output_BasePowerSpectrum.cpp
  src/Output/Output_DumpData_Part.cpp
  src/Output/Output_DumpData_Total_HDF5.cpp
  src/Output/Output_L1Error.cpp
  src/Output/Output_Patch.cpp
  src/Output/Output_PreparedPatch_Fluid.cpp
  src/Particle/Par_Output_TextFile.cpp
  src/SelfGravity/Output_PreparedPatch_Poisson.cpp
Labels: enhancement, output

#243 Unify all the `PRINT_WARNING`
  include/Macro.h
  include/Prototype.h
  include/TestProb.h
  src/GPU_API/CUAPI_SetMemSize.cu
  src/Init/Init_ResetParameter.cpp
  src/SelfGravity/Init_Set_Default_MG_Parameter.cpp
  src/SelfGravity/Init_Set_Default_SOR_Parameter.cpp
  src/TestProblem/ELBDM/ExtPot/Init_TestProb_ELBDM_ExtPot.cpp
  src/TestProblem/Hydro/AGORA_IsolatedGalaxy/Init_TestProb_Hydro_AGORA_IsolatedGalaxy.cpp
  src/TestProblem/Hydro/AcousticWave/Init_TestProb_Hydro_AcousticWave.cpp
  src/TestProblem/Hydro/BlastWave/Init_TestProb_Hydro_BlastWave.cpp
  src/TestProblem/Hydro/Bondi/Init_TestProb_Hydro_Bondi.cpp
  src/TestProblem/Hydro/CDM_LSS/Init_TestProb_Hydro_CDM_LSS.cpp
  src/TestProblem/Hydro/CMZ/Init_TestProb_Hydro_CMZ.cpp
  src/TestProblem/Hydro/Caustic/Init_TestProb_Hydro_Caustic.cpp
  src/TestProblem/Hydro/ClusterMerger/Init_TestProb_ClusterMerger.cpp
  src/TestProblem/Hydro/EnergyPowerSpectrum/Init_TestProb_Hydro_EnergyPowerSpectrum.cpp
  src/TestProblem/Hydro/Gravity/Init_TestProb_Hydro_Gravity.cpp
  src/TestProblem/Hydro/JeansInstability/Init_TestProb_Hydro_JeansInstability.cpp
  src/TestProblem/Hydro/Jet/Init_TestProb_Hydro_Jet.cpp
  src/TestProblem/Hydro/KelvinHelmholtzInstability/Init_TestProb_Hydro_KelvinHelmholtzInstability.cpp
  src/TestProblem/Hydro/MHD_ABC/Init_TestProb_Hydro_MHD_ABC.cpp
  src/TestProblem/Hydro/MHD_LinearWave/Init_TestProb_Hydro_MHD_LinearWave.cpp
  src/TestProblem/Hydro/MHD_OrszagTangVortex/Init_TestProb_Hydro_MHD_OrszagTangVortex.cpp
  src/TestProblem/Hydro/ParticleEquilibriumIC/Init_TestProb_Hydro_ParEqmIC.cpp
  src/TestProblem/Hydro/ParticleTest/Init_TestProb_Hydro_ParticleTest.cpp
  src/TestProblem/Hydro/Plummer/Init_TestProb_Hydro_Plummer.cpp
  src/TestProblem/Hydro/Riemann/Init_TestProb_Hydro_Riemann.cpp
  src/TestProblem/Hydro/SphericalCollapse/Init_TestProb_Hydro_SphericalCollapse.cpp
  src/TestProblem/Hydro/Zeldovich/Init_TestProb_Zeldovich.cpp
  src/TestProblem/Template/Init_TestProb_Template.cpp
Labels: enhancement

#245 `MPI_Alltoallv_GAMER` Wrapper
  include/Prototype.h
  include/Serial.h
  src/Auxiliary/Aux_Check_PatchAllocate.cpp
  src/Feedback/FB_AdvanceDt.cpp
  src/Feedback/SNe/FB_SNe.cpp
  src/Feedback/User_Template/FB_User_Template.cpp
  src/Init/Init_FFTW.cpp
  src/LoadBalance/LB_AllocateBufferPatch_Father.cpp
  src/LoadBalance/LB_AllocateBufferPatch_Sibling.cpp
  src/LoadBalance/LB_AllocateBufferPatch_Sibling_Base.cpp
  src/LoadBalance/LB_ExchangeFlaggedBuffer.cpp
  src/LoadBalance/LB_GetBufferData.cpp
  src/LoadBalance/LB_Init_LoadBalance.cpp
  src/LoadBalance/LB_Output_LBIdx.cpp
  src/LoadBalance/LB_RecordExchangeDataPatchID.cpp
  src/LoadBalance/LB_RecordExchangeRestrictDataPatchID.cpp
  src/LoadBalance/LB_Refine.cpp
  src/LoadBalance/LB_Refine_AllocateNewPatch.cpp
  src/LoadBalance/LB_Refine_GetNewRealPatchList.cpp
  src/MPI/MPI_Alltoallv_GAMER.cpp
  src/Main/Prepare_PatchData.cpp
  src/Makefile
  src/Makefile_base
  src/Miscellaneous/Mis_BinarySearch.cpp
  src/Miscellaneous/Mis_BinarySearch_Real.cpp
  src/Miscellaneous/Mis_Heapsort.cpp
  src/Miscellaneous/Mis_Matching.cpp
  src/Model_Hydro/MHD_LB_Refine_GetCoarseFineInterfaceBField.cpp
  src/Output/Output_BasePowerSpectrum.cpp
  src/Particle/LoadBalance/Par_LB_CollectParticle2OneLevel.cpp
  src/Particle/LoadBalance/Par_LB_CollectParticleFromRealPatch.cpp
  src/Particle/LoadBalance/Par_LB_ExchangeParticleBetweenPatch.cpp
  src/Particle/LoadBalance/Par_LB_RecordExchangeParticlePatchID.cpp
  src/Particle/LoadBalance/Par_LB_SendParticleData.cpp
  src/Particle/Par_FindHomePatch_UniformGrid.cpp
  src/Particle/Par_MassAssignment.cpp
  src/Particle/Par_Sort.cpp
  src/SelfGravity/CPU_Poisson/CPU_PoissonSolver_FFT.cpp
  src/SelfGravity/Poi_GetAverageDensity.cpp
Labels: enhancement, parallel
