Repository gamer-project/gamer, pull requests merged in 2024-03, with the labels that each got.

#289 Improve unphysical check
  include/Prototype.h
  include/Typedef.h
  src/EoS/Gamma/CPU_EoS_Gamma.cpp
  src/EoS/GammaCR/CPU_EoS_GammaCR.cpp
  src/EoS/Isothermal/CPU_EoS_Isothermal.cpp
  src/EoS/User_Template/CPU_EoS_User_Template.cpp
  src/Fluid/Flu_Close.cpp
  src/Fluid/Flu_FixUp_Flux.cpp
  src/Fluid/Flu_Prepare.cpp
  src/Interpolation/Interpolate.cpp
  src/Model_Hydro/CPU_Hydro/CPU_FluidSolver_RTVD.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_ConstrainedTransport.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_DataReconstruction.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_FluUtility.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_FullStepUpdate.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_RiemannSolver_Exact.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_RiemannSolver_HLLC.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_RiemannSolver_HLLD.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_RiemannSolver_HLLE.cpp
  src/Model_Hydro/CPU_Hydro/CPU_Shared_RiemannSolver_Roe.cpp
  src/Model_Hydro/GPU_Hydro/CUFLU_FluidSolver_RTVD.cu
  src/Refine/Flag_Real.cpp
Labels: enhancement, hydro

#266 Support different data precision between `UM_IC/PAR_IC` and the simulation field data
  example/test_problem/Hydro/CDM_LSS/Input__Parameter
  example/test_problem/Template/Input__Parameter
  include/Global.h
  include/HDF5_Typedef.h
  src/Auxiliary/Aux_TakeNote.cpp
  src/Init/Init_ByFile.cpp
  src/Init/Init_ByRestart_HDF5.cpp
  src/Init/Init_Load_Parameter.cpp
  src/Init/Init_ResetParameter.cpp
  src/Main/Main.cpp
  src/Output/Output_DumpData_Total_HDF5.cpp
  src/Particle/Par_Init_ByFile.cpp
Labels: enhancement, general

#291 Call Reloading Script and Jupyter Kernel API for `libyt`
  example/test_problem/Template/Input__Parameter
  include/Global.h
  include/HDF5_Typedef.h
  src/Auxiliary/Aux_TakeNote.cpp
  src/Init/Init_ByRestart_HDF5.cpp
  src/Init/Init_Load_Parameter.cpp
  src/Main/Main.cpp
  src/Output/Output_DumpData_Total_HDF5.cpp
  src/YT/YT_Inline.cpp
  src/configure.py
Labels: enhancement, yt
