Repository gamer-project/gamer, pull requests merged in 2024-02, with the labels that each got.

#282 Refactor particle density preparation
  include/Prototype.h
  src/Main/Prepare_PatchData.cpp
  src/Output/Output_BasePowerSpectrum.cpp
  src/Output/Output_DumpData_Total.cpp
  src/Output/Output_DumpData_Total_HDF5.cpp
  src/Particle/Par_CollectParticle2OneLevel.cpp
  src/SelfGravity/Gra_AdvanceDt.cpp
Labels: enhancement, particle, parallel

#283 Switch from -O3 to -O2 in *.config for the intel compiler
  configs/bluewaters.config
  configs/eureka_intel.config
  configs/ncts.config
  configs/spock_intel.config
Labels: compilation, bugfix

#285 Support _EINT in Prepare_PatchData()
  src/Main/InterpolateGhostZone.cpp
  src/Main/Prepare_PatchData.cpp
Labels: enhancement, general

#286 Generalize Aux_ComputeProfile()
  include/Prototype.h
  src/Auxiliary/Aux_ComputeProfile.cpp
  src/Main/InterpolateGhostZone.cpp
  src/Main/Prepare_PatchData.cpp
Labels: enhancement, general

#287 Hydro/ClusterMerger: correct the attribute to write B_IC file
  example/test_problem/Hydro/ClusterMerger/gamer_cluster_ics.py
Labels: bugfix, test

#288 Set VelR=0 when r==0 in Aux_ComputeProfile()
  src/Auxiliary/Aux_ComputeProfile.cpp
Labels: enhancement, general
