Repository gamer-project/gamer, pull requests merged in 2024-06, with the labels that each got.

#317 [Bugfix] OPT__OUTPUT_TEXT_FORMAT_FLT
  include/Global.h
  src/Init/Init_ResetParameter.cpp
  src/Main/Main.cpp
Labels: bugfix

#319 Update wiki
  doc/wiki/Contribute:-Update-Wiki.md
  doc/wiki/How-to-Contribute.md
Labels: doc

#324 [Bugfix] Deal with FLU_GPU_NPGROUP < OMP_NTHREAD
  src/Model_Hydro/CPU_Hydro/CPU_FluidSolver_CTU.cpp
  src/Model_Hydro/CPU_Hydro/CPU_FluidSolver_MHM.cpp
Labels: bugfix, hydro, parallel, mhd

#329 [Bugfix] Check GPU_COMPUTE_CAPABILITY only when defining GPU
  include/Macro.h
  src/Auxiliary/Aux_TakeNote.cpp
Labels: bugfix, gpu

#327 Add Init_User_AfterPoisson_Ptr
  doc/wiki/Adding-New-Simulations.md
  include/TestProb.h
  src/Init/Init_GAMER.cpp
  src/Init/Init_User.cpp
  src/TestProblem/Template/Init_TestProb_Template.cpp
Labels: enhancement, general
