Repository gamer-project/gamer, pull requests merged in 2025-02, with the labels that each got.

#357 Autocompletion of `configure.py`
  doc/wiki/ELBDM-related/ELBDM-Hybrid-Scheme.md
  doc/wiki/ELBDM-related/ELBDM-Spectral-Solver.md
  doc/wiki/Installation-related/Installation:-Option-List.md
  doc/wiki/Installation.md
  doc/wiki/configure.py.md
  example/test_problem/ELBDM/LSS_Hybrid/generate_make.sh
  example/test_problem/ELBDM/Perturbation/generate_make.sh
  example/test_problem/ELBDM/Perturbation/generate_make_BaseSpectral.sh
  example/test_problem/ELBDM/VortexPairLinear_Hybrid/generate_make.sh
  example/test_problem/ELBDM/VortexPairRotating_Hybrid/generate_make.sh
  example/test_problem/Hydro/AGORA_IsolatedGalaxy/generate_make.sh
  example/test_problem/Hydro/Bondi/generate_make.sh
  example/test_problem/Hydro/SphericalCollapse/generate_make.sh
  example/test_problem/Hydro/Zeldovich/README
  example/test_problem/Hydro/Zeldovich/generate_make.sh
  src/Makefile_base
  src/configure.py
  tool/config/config_autocomplete.sh
Labels: enhancement, compilation

#430 [Bugfix] Fix #425
  doc/wiki/Adding-Parameters.md
  include/Global.h
  src/Auxiliary/Aux_Check_Conservation.cpp
  src/Auxiliary/Aux_Check_Parameter.cpp
  src/Auxiliary/Aux_GetMemInfo.cpp
  src/Auxiliary/Aux_Record_Center.cpp
  src/Auxiliary/Aux_Record_CorrUnphy.cpp
  src/Auxiliary/Aux_Record_PatchCount.cpp
  src/Auxiliary/Aux_Record_Performance.cpp
  src/Auxiliary/Aux_Record_User.cpp
  src/Auxiliary/Aux_TakeNote.cpp
  src/Auxiliary/Aux_Timing.cpp
  src/Fluid/Flu_Close.cpp
  src/GPU_API/CUAPI_DiagnoseDevice.cu
  src/LoadBalance/LB_EstimateLoadImbalance.cpp
  src/LoadBalance/LB_GetBufferData.cpp
  src/Main/Main.cpp
  src/Miscellaneous/Mis_GetTimeStep.cpp
  src/Model_ELBDM/ELBDM_Aux_Record_Hybrid.cpp
  src/Model_Hydro/MHD_Aux_Check_DivergenceB.cpp
  src/Output/Output_BoundaryFlagList.cpp
  src/Output/Output_DumpData.cpp
  src/Output/Output_ExchangeDataPatchList.cpp
  src/Output/Output_ExchangeFluxPatchList.cpp
  src/Output/Output_ExchangePatchMap.cpp
  src/Output/Output_FlagMap.cpp
  src/Output/Output_Flux.cpp
  src/Output/Output_L1Error.cpp
  src/Output/Output_Patch.cpp
  src/Output/Output_PatchCorner.cpp
  src/Output/Output_PatchMap.cpp
  src/Output/Output_PreparedPatch_Fluid.cpp
  src/Particle/LoadBalance/Par_LB_SendParticleData.cpp
  src/Particle/Par_Aux_Record_ParticleCount.cpp
  src/TestProblem/Hydro/Bondi/Record_Bondi.cpp
  src/TestProblem/Hydro/Gravity/Init_TestProb_Hydro_Gravity.cpp
Labels: bugfix, general

#314 Store conserved variable values to HDF5
  include/Global.h
  include/HDF5_Typedef.h
  include/Macro.h
  src/Auxiliary/Aux_Check.cpp
  src/Auxiliary/Aux_Check_Conservation.cpp
  src/Auxiliary/Aux_Check_Parameter.cpp
  src/Auxiliary/Aux_TakeNote.cpp
  src/Init/Init_ByRestart_HDF5.cpp
  src/Init/Init_ResetParameter.cpp
  src/Main/Main.cpp
  src/Output/Output_DumpData_Total_HDF5.cpp
Labels: enhancement, test, output

#426 Update libyt codes to support particle integer attributes
  src/YT/YT_AddLocalGrid.cpp
  src/YT/YT_DerivedFunction.cpp
  src/YT/YT_GetParticleAttribute.cpp
  src/YT/YT_Init.cpp
  src/YT/YT_Inline.cpp
  src/YT/YT_Miscellaneous.cpp
  src/YT/YT_SetParameter.cpp
Labels: enhancement, yt

#399 [Bugfix] SwitchFinerLevelsToWaveScheme in Refine.cpp
  src/Refine/Refine.cpp
Labels: bugfix, amr, fdm

#437 Update fomalhaut.config
  configs/fomalhaut.config
  example/queue/submit_fomalhaut.job
Labels: enhancement, compilation
